### ISSUE TITLE
All sources are only matched to a single external catalog

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#78]
(for processed data from 20221204, M2C1)

In catalog files, the column 'MergedCatMask' only takes on 6 different values that correspond to:

['GAIA-EDR3']
['unWISE']
['2MASS']
['SDSS-DR10']
['PS1-DR1']
['ztfDR1var']

I would have expected that most sources are in several external catalogs and not just a single one.

**Comment by noralinn** [comment]
This is caused by using the option 'SwitchRefCat'. Line 272 of pipeline.generic.procMergeCoadd is:

Coadd = imProc.match.match_catsHTMmerged(Coadd, 'SameField',false, 'CreateNewObj',false, 'SwitchRefCat',true);

And setting 'SwitchRefCat' to false returns different, better looking values for 'MergeCatMask'. (But I didn't check if they are actually correct.)

So the bug is likely in imProc.match.match_catsHTMmerged near line 85.

**Comment by EranOfek** [comment]
One a few cases, I compared the output of the SwitchRefCat=true/false and I see no difference.
Furthermore, in most cases, the sources are associated with more than one external catalog which is a good sign.
In the case I inspected there are 26 unique combinations of catalogs...

Maybe this is an old bug in the code that was fixed?
Please keep an eye on this

**Comment by noralinn** [comment]
I pulled from github (on last04e) and I'm still get the same difference as before. Maybe I'm not using it correctly? Or the results don't mean what I think they do?


% cross matching without switching
AC=AstroCatalog({'LAST.01.02.01_20221204.163429.244_clear_331+42_001_001_023_sci_coadd_Cat_1.fits'},'HDU',2);
>> Coadd = imProc.match.match_catsHTMmerged(AC,'SwitchRefCat',false) 
>> Coadd.Catalog(1:20,54)

ans =

        4167
          79
          71
          71
          71
          71
          71
          71
          71
          71
          71
          71
          71
          71
          71
          71
          71
          71
          71
          71

% after cross matching with switching; this one looks bad
>> AC2=AstroCatalog({'LAST.01.02.01_20221204.163429.244_clear_331+42_001_001_023_sci_coadd_Cat_1.fits'},'HDU',2);
>> Coadd2 = imProc.match.match_catsHTMmerged(AC2,'SwitchRefCat',true);
>> Coadd2.Catalog(1:20,54)

ans =

     2
     1
     1
     1
     1
     1
     4
     4
     1
     1
     1
     1
     1
     1
    64
     2
     1
     1
     1
     2

**Comment by EranOfek** [comment]
was able to recover bug - switch code to SwitchRefCat=false.
I will ask Chen to write a mex version of the slow code.
